### ISSUE TITLE
Request for clarifications in the README

### ISSUE THREAD

**Issue by designatednerd** [jitpack/android-example#1]
Hi there! Wondering if you can clarify some of the required steps to get this to work with Android - I've been fighting with this for some time and I still can't quite seem to get it to work. 
- Does the project you wish to use for creating the lib need to be in the root of the repo, or can it be in a secondary folder? 
- Can I use the `include:library` notation in my `settings.gradle` file, or do I need to use direct file references as shown [here](https://github.com/PhilJay/MPAndroidChart/blob/master/settings.gradle)? 
- Where do I run `gradle install` - on the project where I've created the library, or on the project where I'm attempting to add the library? 
- Does the `android-maven` plugin need to be applied to both the project where I've created the library, the project where I'm attempting to add the library, or both? 

Any clarifications on any of these would be most helpful. It would be really helpful if you could update the README to give a step-by-step set of instructions as to how to set up your repo so that jitpack will recognize it - I feel like I'm missing something big here. Thanks!

**Comment by jitpack-io** [comment]
Hi @designatednerd 

- The project can be in a sub-folder
- `include:library` is known to work. It might be possible to use something else as long as `gradle install` works.
- `gradle install` should be working on the project where you have the library.
- `android-maven` is only necessary in the library project.

The most important part is that your library jar/aar installs in the local maven repository ($HOME/.m2/repository). The easiest way to get it there is to apply the `android-maven` plugin to the library and run `gradle install`.

Thanks for the questions! Will be updating the README based on this.

**Comment by designatednerd** [comment]
Awesome, thank you! :+1:
