### ISSUE TITLE
android-maven-gradle-plugin version update

### ISSUE THREAD

**Issue by douglasjunior** [jitpack/android-example#12]
Please, update version of [android-maven-gradle-plugin](https://github.com/dcendents/android-maven-gradle-plugin) to work with most recent version of gradle.

Thanks.

**Comment by Jawnnypoo** [comment]
This can now be closed since https://github.com/jitpack/android-example/pull/11 was merged

**Comment by jitpack-io** [comment]
Thanks @Jawnnypoo !
