### ISSUE TITLE
Specifying build variants

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/android-example#2]
Hi there @jitpack-io ,

is it possible to specify a build variant to be generated the library using jitpack? 

In my library I have two build variants (for example, sandbox and production), how can I specify which of them I want to build?

Thanks

**Comment by jitpack-io** [comment]
It should be possible to build multiple variants during the same build but as different artifacts. Something along the lines of https://github.com/jitpack/android-example/blob/master/library/build.gradle#L36-L42

Would you have an example project on GitHub with multiple variants?

**Comment by jitpack-io** [comment]
@SandroMachado Are the variants configured using `productFlavors `? http://stackoverflow.com/a/24910671/3975649
Just looking for an example to try jitpack on.

**Comment by SandroMachado** [comment]
@jitpack-io Yes, you can find the official documentation here: http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants

If necessary I can build just a demo lib with Product Flavours/Build Variants. Please let me know.

**Comment by jitpack-io** [comment]
@SandroMachado A demo lib would be really great.

**Comment by SandroMachado** [comment]
@jitpack-io I made a demo library. How can I integrate the demo library (https://github.com/SandroMachado/android-jitpack-library-example) and choose the sandbox flavour?

**Comment by jitpack-io** [comment]
@SandroMachado Thanks! Trying it out...

**Comment by jitpack-io** [comment]
@SandroMachado Done! Got it to publish all variants and you can include whichever one is needed.
See the README in my forked project: https://github.com/jitpack-io/android-jitpack-library-example

And this is the commit to enable publishing all variants: https://github.com/jitpack-io/android-jitpack-library-example/commit/c71bdb4ba76108aa89a7d87da24336d92881c86d

**Comment by SandroMachado** [comment]
Great! @jitpack-io thanks!
