### ISSUE TITLE
Not work with Gradle 7.0

### ISSUE THREAD

**Issue by CuiTianci** [jitpack/android-example#27]
Error log on Jitpack.io
* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by liuxiaoliu66** [comment]
这个maven插件已经不更新了，似乎只能去使用maven-publish插件l

**Comment by CuiTianci** [comment]
A jitpack.yml file which contains 
jdk:
  - openjdk11
 should be added to the root of the project when gradle7.0 is used.

**Comment by liuxiaoliu66** [comment]
Have you found a way to work on gradle7.0?

**Comment by CuiTianci** [comment]
> Have you found a way to work on gradle7.0?
在项目根目录下添加一个jitpcak.yml文件，就像这样：
https://github.com/CuiTianci/SelectableTextView/blob/master/jitpack.yml

**Comment by CuiTianci** [comment]
> Have you found a way to work on gradle7.0?

在项目根目录下添加一个jitpack.yml文件，指定jdk版本，文件内容如下：
https://github.com/CuiTianci/SelectableTextView/blob/master/jitpack.yml
